### ISSUE TITLE
study with empty tree

### ISSUE THREAD

**Issue by ghost** [TreeBASE/treebase#259] opened 2015-06-25 14:21 UTC
The second tree in http://treebase.org/treebase-web/search/study/summary.html?id=14763
is empty in NEXUS and just has one node in NeXML.

Reported by: mholder

**Comment by rvosa** [comment] 2017-07-20 00:41
Sorry, can't reproduce. The second tree (18S-Treb) comes out fine as Nexus and NeXML. Provisionally closing this, feel free to reopen if this is reproducible.

**Closed by rvosa** 2017-07-20 00:41 UTC
Labels: auto-migrated, easy, sourceforge
